{% set name = "multivisor" %}
{% set version = "6.0.2" %}

package:
  name: multivisor-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multivisor-{{ version }}.tar.gz
  sha256: 247bd964b515be41d843f7d59159fada8f30405eb279cb55d66ef0cf141ae677

build:
  number: 0

outputs:
  - name: multivisor
    script: build_core.sh
    build:
      noarch: python
      entry_points:
        - multivisor=multivisor.server.web:main
        - multivisor-rpc=multivisor.server.rpc:main
        - multivisor-cli=multivisor.client.cli:main
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - gevent >=1.3
        - python >={{ python_min }}
        - six
    test:
      imports:
        - multivisor
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: multivisor-web
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('multivisor', max_pin='x.x.x.x') }}
        - flask
        - werkzeug <2.1
        - blinker
        - zerorpc-python
        - supervisor
    test:
      requires:
        - python {{ python_min }}
      imports:
        - multivisor.server.web
      commands:
        - multivisor --help

  - name: multivisor-rpc
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('multivisor', max_pin='x.x.x.x') }}
        - zerorpc-python
        - supervisor
    test:
      requires:
        - python {{ python_min }}
      imports:
        - multivisor.server.rpc
      commands:
        - multivisor-rpc --help

  - name: multivisor-cli
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('multivisor', max_pin='x.x.x.x') }}
        - maya
        - requests
        - prompt_toolkit >=2
        - blinker
    test:
      requires:
        - python {{ python_min }}
      imports:
        - multivisor.client.cli
      commands:
        - multivisor-cli --help

about:
  home: https://github.com/tiagocoutinho/multivisor
  summary: A centralized supervisor UI (web & CLI)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  feedstock-name: multivisor
  recipe-maintainers:
    - beenje
