schema_version: 1

context:
  name: multivisor
  version: "7.1.0"

recipe:
  name: multivisor-suite
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/multivisor-${{ version }}.tar.gz
  sha256: d33a34b5c6cc0957a0855c2da65f42f29cea3df8154a1dacc4b6ced8403ed649

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: multivisor
    build:
      noarch: python
      python:
        entry_points:
          - multivisor=multivisor.server.web:main
          - multivisor-rpc=multivisor.server.rpc:main
          - multivisor-cli=multivisor.client.cli:main
      script: ${{ PYTHON }} -m pip install --no-deps -vv .
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
        - setuptools-scm
      run:
        - gevent >=1.3
        - python >=${{ python_min }}
    tests:
      - python:
          imports:
            - multivisor
          python_version:
            - ${{ python_min }}.*
            - 3.*
          pip_check: true
  - package:
      name: multivisor-web
    build:
      noarch: generic
    requirements:
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('multivisor', exact=True) }}
        - flask
        - flask-cors
        - werkzeug
        - blinker
        - pyzmq
        - msgpack-python
        - supervisor
    tests:
      - python:
          imports:
            - multivisor.server.web
          python_version:
            - ${{ python_min }}.*
            - 3.*
      - script:
          - multivisor --help
        requirements:
          run:
            - python ${{ python_min }}.*
  - package:
      name: multivisor-rpc
    build:
      noarch: generic
    requirements:
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('multivisor', exact=True) }}
        - pyzmq
        - msgpack-python
        - supervisor
    tests:
      - python:
          imports:
            - multivisor.server.rpc
          python_version:
            - ${{ python_min }}.*
            - 3.*
      - script:
          - multivisor-rpc --help
        requirements:
          run:
            - python ${{ python_min }}.*
  - package:
      name: multivisor-cli
    build:
      noarch: generic
    requirements:
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('multivisor', exact=True) }}
        - maya
        - requests
        - prompt_toolkit >=2
        - blinker
    tests:
      - python:
          imports:
            - multivisor.client.cli
          python_version:
            - ${{ python_min }}.*
            # WARNING: pendulum <=3.1.0 not compatible with python 3.14
            - 3.13.*
      - script:
          - multivisor-cli --help
        requirements:
          run:
            - python ${{ python_min }}.*

about:
  summary: A centralized supervisor UI (web & CLI)
  license: GPL-3.0-or-later AND MIT
  license_file:
    - LICENSE
    - multivisor/zerorpc/LICENSE
  homepage: https://github.com/tiagocoutinho/multivisor

extra:
  feedstock-name: multivisor
  recipe-maintainers:
    - beenje
